In [1]:
import numpy as np
a =np.array([1,3,5,7,9])
a *=10
a

array([10, 30, 50, 70, 90])

In [2]:
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

a+b

array([ 3,  7, 11, 15, 19])

In [3]:
arr = np.array([ [1,3,5],[2,4,6] ])
arr.ndim #j
arr.shape #
arr.size #
arr.dtype #

dtype('int64')

In [4]:
np.random.rand()
np.random.rand(30, 4)

array([[0.18194313, 0.81382164, 0.61487289, 0.77019766],
       [0.96036165, 0.12906152, 0.05440371, 0.44247543],
       [0.82916558, 0.76278564, 0.5366889 , 0.08137386],
       [0.25929454, 0.24521893, 0.53641726, 0.37692734],
       [0.40023019, 0.49973   , 0.63245066, 0.94436118],
       [0.12299147, 0.82977373, 0.81721548, 0.16312876],
       [0.51914752, 0.5484428 , 0.43732926, 0.2401913 ],
       [0.53370508, 0.99373225, 0.39594825, 0.65122298],
       [0.78301793, 0.82174556, 0.4068683 , 0.57079824],
       [0.46024291, 0.48417668, 0.65175492, 0.66145624],
       [0.6514244 , 0.46663289, 0.98749532, 0.4158021 ],
       [0.28567348, 0.10928971, 0.00726805, 0.12613204],
       [0.62157205, 0.24969655, 0.09456413, 0.10233   ],
       [0.90274037, 0.4480586 , 0.55284993, 0.60305941],
       [0.66852399, 0.5975334 , 0.25085088, 0.96327987],
       [0.83212797, 0.78048182, 0.58469638, 0.79044185],
       [0.43041303, 0.54700459, 0.56964934, 0.24434658],
       [0.66492769, 0.84925845,

In [5]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 88,  73,  71,  70,  75],
       [ 88,  94,  50,  63,  70],
       [ 71,  78,  69,  96,  75],
       [ 76,  63,  59,  72,  66],
       [ 62,  66,  88,  68,  79],
       [ 78,  87,  75,  71,  62],
       [ 88,  93,  70,  55,  79],
       [ 66,  96,  77,  99,  94],
       [100,  76,  74,  95,  67],
       [ 53,  81,  58,  57,  57],
       [ 93,  60,  51,  91,  97],
       [ 65,  79,  85,  92,  88],
       [ 53,  59,  86,  69,  96],
       [ 92,  81,  53,  86,  94],
       [ 58,  50,  73,  87,  50],
       [ 91,  93,  73,  97,  65],
       [ 94,  54,  50,  52,  60],
       [ 62,  58,  67,  53,  89],
       [ 65,  95,  80,  59,  91],
       [ 77,  52,  95,  60,  63],
       [ 86,  99,  60,  66,  52],
       [ 55,  91,  81,  55,  81],
       [ 66,  98,  67,  68,  53],
       [ 68,  63,  56,  50,  55],
       [ 95,  80,  96,  90,  93],
       [ 52,  90,  75,  58,  71],
       [ 91,  77,  66,  81,  67],
       [ 73,  80, 100,  94,  51],
       [ 60,  75,  96,  87,  88],
       [ 97,  

In [7]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個
arr[5:-5]

array([], dtype=int64)