In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個


array([50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50, 101,size=(50,5))
scores



array([[ 84,  53,  54,  61,  99],
       [ 51,  56,  99,  94,  63],
       [ 91,  66,  83,  61,  95],
       [ 61, 100,  72,  94,  63],
       [ 96,  53,  98,  62,  50],
       [ 82,  75,  79,  91,  98],
       [ 89,  60,  53,  93,  88],
       [ 64,  95,  88,  70,  71],
       [ 81,  71,  88,  70,  99],
       [ 95,  56, 100,  51,  93],
       [ 56,  62,  80,  57,  62],
       [ 79,  88,  70,  52,  84],
       [ 80,  59,  75,  56,  52],
       [ 62,  61,  76,  82,  66],
       [ 64,  68,  63,  79,  50],
       [ 67,  53,  71,  78,  59],
       [ 76,  99,  93, 100,  82],
       [ 86,  99,  72,  72,  73],
       [ 51,  59,  59,  56,  56],
       [ 92,  67,  86,  59,  71],
       [ 70,  58,  59,  74,  58],
       [ 98,  66,  97,  81,  55],
       [ 77,  63,  94,  97,  80],
       [ 86,  55,  57,  80,  99],
       [ 94,  58,  79,  59,  79],
       [ 87,  87,  80,  97,  78],
       [ 98,  63,  79,  63,  52],
       [ 92,  52,  62,  83,  53],
       [ 64,  80,  96,  53,  86],
       [ 96,  

In [10]:
scores [5,:]

array([82, 75, 79, 91, 98], dtype=int32)

In [12]:
scores [:,0]
scores [:,1]
scores [:,2]

array([ 54,  99,  83,  72,  98,  79,  53,  88,  88, 100,  80,  70,  75,
        76,  63,  71,  93,  72,  59,  86,  59,  97,  94,  57,  79,  80,
        79,  62,  96,  95,  81,  72,  73,  92,  85,  69,  68,  96,  78,
        68,  50,  88,  51,  95,  93,  80,  50,  93,  78,  98], dtype=int32)

In [21]:
total=scores [:,0] + scores[:,1] + scores [:,2] + scores [:,3] +scores [:,4]
total

array([351, 363, 396, 390, 359, 425, 383, 388, 409, 395, 317, 373, 322,
       347, 324, 328, 450, 402, 281, 375, 319, 397, 411, 377, 369, 429,
       355, 342, 379, 434, 393, 409, 355, 409, 359, 335, 390, 391, 407,
       394, 322, 429, 392, 420, 388, 372, 327, 344, 441, 399], dtype=int32)

In [23]:
total /5

array([70.2, 72.6, 79.2, 78. , 71.8, 85. , 76.6, 77.6, 81.8, 79. , 63.4,
       74.6, 64.4, 69.4, 64.8, 65.6, 90. , 80.4, 56.2, 75. , 63.8, 79.4,
       82.2, 75.4, 73.8, 85.8, 71. , 68.4, 75.8, 86.8, 78.6, 81.8, 71. ,
       81.8, 71.8, 67. , 78. , 78.2, 81.4, 78.8, 64.4, 85.8, 78.4, 84. ,
       77.6, 74.4, 65.4, 68.8, 88.2, 79.8])

In [24]:
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([70.2, 72.6, 79.2, 78. , 71.8, 85. , 76.6, 77.6, 81.8, 79. , 63.4,
       74.6, 64.4, 69.4, 64.8, 65.6, 90. , 80.4, 56.2, 75. , 63.8, 79.4,
       82.2, 75.4, 73.8, 85.8, 71. , 68.4, 75.8, 86.8, 78.6, 81.8, 71. ,
       81.8, 71.8, 67. , 78. , 78.2, 81.4, 78.8, 64.4, 85.8, 78.4, 84. ,
       77.6, 74.4, 65.4, 68.8, 88.2, 79.8])

In [25]:
scores.sum(axis=1)
scores.mean(axis=1)

array([70.2, 72.6, 79.2, 78. , 71.8, 85. , 76.6, 77.6, 81.8, 79. , 63.4,
       74.6, 64.4, 69.4, 64.8, 65.6, 90. , 80.4, 56.2, 75. , 63.8, 79.4,
       82.2, 75.4, 73.8, 85.8, 71. , 68.4, 75.8, 86.8, 78.6, 81.8, 71. ,
       81.8, 71.8, 67. , 78. , 78.2, 81.4, 78.8, 64.4, 85.8, 78.4, 84. ,
       77.6, 74.4, 65.4, 68.8, 88.2, 79.8])